# Generated by Django 5.0.6 on 2024-06-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_1',
            fields=[
                ('id', models.IntegerField(max_length=2, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('tags', models.CharField(choices=[('TC', 'Technology'), ('HE', 'Health'), ('TR', 'Travel'), ('FO', 'Food'), ('LI', 'Lifestyle')], max_length=10)),
            ],
        ),
    ]
